//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShimGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShimGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Memory DLL loading code
        /// * Version 0.0.4
        /// *
        /// * Copyright (c) 2004-2015 by Joachim Bauch / mail@joachim-bauch.de
        /// * http://www.joachim-bauch.de
        /// *
        /// * The contents of this file are subject to the Mozilla Public License Version
        /// * 2.0 (the &quot;License&quot;); you may not use this file except in compliance with
        /// * the License. You may obtain a copy of the License at
        /// * http://www.mozilla.org/MPL/
        /// *
        /// * Software distributed under the License is distributed on an &quot;AS IS&quot; basis,
        /// * WITHOUT WARRANTY OF ANY KIND, eith [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MemoryModule_c {
            get {
                return ResourceManager.GetString("MemoryModule_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Memory DLL loading code
        /// * Version 0.0.4
        /// *
        /// * Copyright (c) 2004-2015 by Joachim Bauch / mail@joachim-bauch.de
        /// * http://www.joachim-bauch.de
        /// *
        /// * The contents of this file are subject to the Mozilla Public License Version
        /// * 2.0 (the &quot;License&quot;); you may not use this file except in compliance with
        /// * the License. You may obtain a copy of the License at
        /// * http://www.mozilla.org/MPL/
        /// *
        /// * Software distributed under the License is distributed on an &quot;AS IS&quot; basis,
        /// * WITHOUT WARRANTY OF ANY KIND, eith [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MemoryModule_h {
            get {
                return ResourceManager.GetString("MemoryModule_h", resourceCulture);
            }
        }
    }
}
